services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BOOTSTRAP_SERVERS},PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    profiles: [ "local", "dev" ]
    ports:
      - "${KAFKA_UI_PORT:-9000}:8080"
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:29092}
    networks:
      - backend-network

  db:
    image: postgres:latest
    container_name: postgres
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-USR_LEILAO}
      POSTGRES_PASSWORD: ${DB_PSW:-Senha1234}
      POSTGRES_DB: ${DB:-banco_de_dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-USR_LEILAO} -d $${POSTGRES_DB:-banco_de_dev}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - backend-network

  ui:
    container_name: leilao-ui
    build:
      context: ./leilao-ui
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    networks:
      - frontend-network
    depends_on:
      api:
        condition: service_started

  api:
    container_name: leilao-api
    build:
      context: ./leilao-api
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - URL_ACCESS=${URL_ACCESS:-http://localhost:4200}
      - SPRING_PROFILE=${COMPOSE_PROFILES:-dev}
      - SPRING_DATASOURCE_URL=jdbc:${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB:-banco_de_dev}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-USR_LEILAO}
      - SPRING_DATASOURCE_PASSWORD=${DB_PSW:-Senha1234}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:29092}
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  consumer:
    container_name: leilao-consumer
    build:
      context: ./leilao-consumer
    environment:
      - SPRING_PROFILE=${COMPOSE_PROFILES:-dev}
      - SPRING_DATASOURCE_URL=jdbc:${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB:-banco_de_dev}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-USR_LEILAO}
      - SPRING_DATASOURCE_PASSWORD=${DB_PSW:-Senha1234}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:29092}
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
