spring:
  application:
    name: leilao-consumer
  profiles:
    active: @spring.profiles.active@
  cloud:
    function:
      definition: auctionConsumer
    stream:
      kafka:
          binder:
              brokers: ${KAFKA_BOOTSTRAP_SERVERS}
          bindings:
            auctionConsumer-in-0:
              consumer:
                enable-dlq: true
                dlq-name: auction-dlq
      bindings:
        auctionConsumer-in-0:
          destination: auction
          group: auctions
          consumer:
            concurrency: 1
            max-attempts: 3
