services:
  graphql-service:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
        - GRAPHQL_PORT=${GRAPHQL_PORT:-4000}
    container_name: graphql-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
      - graphql-network

networks:
  kafka-network:
    external: true
    name: kafka-network
  graphql-network:
    external: true
    name: graphql-network
