spring:
  application:
    name: leilao-api
  profiles:
    active: @spring.profiles.active@

  cloud:
    stream:
      bindings:
        producerOrder-out-0:
          destination: order-created

  graphql:
    cors:
      allowed-origins: ${URL_ACCESS}
      allowed-methods: "*"
    graphiql:
      enabled: true
      path: /graphiql
